#!/usr/bin/env bash

set -e

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pushd $dir > /dev/null

function finish {
    rm -fr ./ssh-out-of-git
    popd
}

trap finish EXIT

## MacOS stuff

if [[ $OSTYPE =~ "darwin" ]]
then
  echo "MacOS type build."
  sudo=
  sed="sed -i -e"
else
  echo "Default type build."
  sudo=sudo
  sed="sed -i"
fi

## stuff for dockerfile


USER=`whoami`

date > cachebuster-out-of-git
$sed "s/ENV THE_USER=.*/ENV THE_USER=$USER/" ./Dockerfile
$sed "s/ENV THE_UID=.*/ENV THE_UID=$UID/" ./Dockerfile

$sudo docker pull ubuntu
cp -r $HOME/.ssh ./ssh-out-of-git
$sudo docker build -t freakhill-dev ./

echo "COMPLETE!"
