#!/usr/bin/env bash

case $OSTYPE in
  darwin*)
	  SUDO()
	  {
		  $*
	  }
    VOLUME_OPTS=":delegated"
    ;;
  linux-gnu*)
	  SUDO()
	  {
		  sudo -E PATH="$PATH" $*
	  }
    ;;
  cygwin)
	  SUDO()
	  {
		  $*
	  }
    ;;
  msys)
	  SUDO()
	  {
		  $*
	  }
    ;;
  win32)
	  SUDO()
	  {
		  $*
	  }
    ;;
  *)
	  SUDO()
	  {
		  $*
	  }
    ;;
esac

if type -a bc
then
    random_token=$(echo "obase=16; $RANDOM" | bc)
else
    random_token=$RANDOM
fi

NAME="fkdev-$RANDOM"

#$sudo docker stop "$NAME" &2>/dev/null && sleep 5 || true
#$sudo docker rm "$NAME" &2>/dev/null && sleep 5 || true
SUDO docker run -d \
      --privileged \
      --name "$NAME" \
      --label jojomachine=true \
      -h "$NAME" \
      -p 10022:10022 \
      -p 22000-22099:22000-22099/udp \
      -p 21000-21099:21000-21099/tcp \
      -p 8000-8100:8000-8100/tcp \
      -v "$HOME":/m$VOLUME_OPTS \
      -v /:/host \
      freakhill-dev

