#!/usr/bin/env bash

case $OSTYPE in
  darwin*)
    sudo=
    ;;
  *)
    sudo=sudo
    ;;
esac

#if type -a bc
#then
#    random_token=$(echo "obase=16; $RANDOM" | bc)
#else
#    random_token=$RANDOM
#fi

NAME="fkdev"

$sudo docker stop "$NAME" &2>/dev/null || true
$sudo docker rm "$NAME" &2>/dev/null || true
$sudo docker run -d \
      --privileged \
      --name "$NAME" \
      -h "$NAME" \
      -p 10022:10022 \
      -p 22000-22099:22000-22099/udp \
      -p 21000-21099:21000-21099/tcp \
      -p 8000-8100:8000-8100/tcp \
      -v "$HOME":/m \
      -v /:/host \
      freakhill-dev
